pipeline {
    agent any        
    stages {
        stage('Checkout-git'){            
            steps{
                echo 'Revisando repositorio del Proyecto Kaizen'
                git poll: true, url: 'https://github.com/kaizenportal/jenkinsfile-maven-junit.git'
            } 
        }    
        stage('Build') {
            steps {
		bat 'C:\\maven-3.6.2\\bin\\mvn -B -DskipTests clean package'
                //sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                try {
                    bat 'C:\\maven-3.6.2\\bin\\mvn test'
                    //sh 'mvn test'
                } catch (Exception e) {
                    bat 'Ha fallado el test unitario!'
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
		echo 'Deploy del jar'
		bat 'java -jar target/my-app-1.0-SNAPSHOT.jar --httpPort=8082'
                //sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}

