pipeline {
    agent any /*{*/
       /* docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }*/
    /*}*/
    stages {
		stage('Checkout-git'){
            /* when {
                    branch 'master'
             }*/
               steps{
                echo 'Revisando repositorio del Proyecto Kaizen'
					git poll: true, url: 'https://github.com/kaizenportal/jenkinsfile-maven-junit.git'
               }
        }
        stage('Build') {
            steps {
				bat 'C:\\maven-3.6.2\\bin\\mvn -B -DskipTests clean package'
                //sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
				bat 'C:\\maven-3.6.2\\bin\\mvn test'
                //sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
				echo 'Deploy del jar'
				//bat 'java -jar target/'
                //sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
